print("Reglas: Piedra, papel o tijera")
print("==============================")
print("1. Se puede jugar entre dos personas")
print("2. Existen tres posibles movimientos con la mano:")
print("   - Piedra representado por la mano cerrada o un puño.")
print("   - Papel, representado por la mano extendida")
print("   - Tijera, representado por los dedos extendidos de la mano en forma de V")
print("3. Solo existe un resultado final:")
print("    * La piedra gana a las tijeras.")
print("    * Las tijeras ganan al papel.")
print("    * Y el papel gana a la piedra")
print("4. Los judadores se deben poner uno frente al otro, con una mano en la espalda")
print("5. Al decir: piedra papel o tijera")
print("6. Deben mostrarlo al mismo tiempo con la mano, el movimiento seleccionado")
print("7. Y veran quien gana, con las reglas descritas previamente.")
print("8. Si los dos han seleccionado el mismo movimiento, entonces hay un empate")
print("9. Y se puede volver a jugar")


