print("===== Tutorial para barrer un cuarto  =====")
print("Empezamos por ubicar las sillas y muebles pequeños encima de la cama")
print("Si es posible, sacar algunos muebles, los que se pueda fuera de la habitacion")
print("Si hay cosas en el piso, recoger y colocar en su lugar")
print("Para empezar a barrer")
print("Agarrar la escoba")
print("Diriguirse hacia el primer lado de la habitacion")

print("Paso-1")
print("Sujeta la escoba con ambas manos")
print("Coloca una mano arriba y la otra mano cerca del centro del palo de la escoba")
print("Arrastra la cabeza de la escoba por el suelo, con movimientos cortos y delineados")
print("Haciendo esto, empujar cualquier residuo del suelo con las cerdas de la escoba")
print("Mueve desde lejos del cuerpo hacia adentro")
print("dar un paso hacia atraz")

print("Verificar, si no estas al medio de la habitacion, entones volver al Paso-1")

print("Verificar, si has llegado al centro de la habitacion")
print("Tomar la escoba")
print("Diriguirse hacia el segundo lado de la habitacion")

print("Paso-2")
print("Sujeta la escoba con ambas manos")
print("Coloca una mano arriba y la otra mano cerca del centro del palo de la escoba")
print("Arrastra la cabeza de la escoba por el suelo, con movimientos cortos y delineados")
print("Haciendo esto, empujar cualquier residuo del suelo con las cerdas de la escoba")
print("Mueve desde lejos del cuerpo hacia adentro")
print("dar un paso hacia atraz")

print("Verificar, si no estas al medio de la habitacion, entones volver al Paso-2")
print("Verificar, si has llegado al centro de la habitacion, continuar.")
print("Tomar la escoba")
print("Diriguirse hacia el tercer lado de la habitacion")

print("Paso-3")
print("Sujeta la escoba con ambas manos")
print("Coloca una mano arriba y la otra mano cerca del centro del palo de la escoba")
print("Arrastra la cabeza de la escoba por el suelo, con movimientos cortos y delineados")
print("Haciendo esto, empujar cualquier residuo del suelo con las cerdas de la escoba")
print("Mueve desde lejos del cuerpo hacia adentro")
print("dar un paso hacia atraz")

print("Verificar, si no estas al medio de la habitacion, entones volver al Paso-3")
print("Verificar, si has llegado al centro de la habitacion, continuar..")
print("Tomar la escoba")
print("Diriguirse hacia el cuarto y ultimo lado de la habitacion")

print("Paso-4")
print("Sujeta la escoba con ambas manos")
print("Coloca una mano arriba y la otra mano cerca del centro del palo de la escoba")
print("Arrastra la cabeza de la escoba por el suelo, con movimientos cortos y delineados")
print("Haciendo esto, empujar cualquier residuo del suelo con las cerdas de la escoba")
print("Mueve desde lejos del cuerpo hacia adentro")
print("da un paso hacia atraz")
print("Verificar, si no estas al medio de la habitacion, entones volver al Paso-4")

print("Verificar, si has llegado al centro de la habitacion")
print("Continuar arrastrando los residuos, hasta formar una pila de residuos")
print("Recoger estos residuos con una pala")
print("Tomar la pala con la mano izquierda y la escoba con la mano derecha")
print("Colocar la pala al costado de la pila de basura")
print("Arrastrar con la escoba los residuos de basura hacia la pala")
print("Levantar la pala con cuidado")
print("Vaciar el contenido de la pala en un contenedor de basura")

print("!!Y LISTO")

